### ISSUE TITLE
Change Sidebar in Mobile View

### ISSUE THREAD

**Issue by nsavinda** [IEEEUCSC/madhack-2024#49]
1. Colors
2. Automatically hide the navbar when navigating
3. Test in different devices

**Comment by lakshith-403** [comment]
fc843774fe71c7eb26d4504065cb530d543da576

93bc0f0ddf16527a4fe13ae559e8b3414f45570f

422769573a946a72be259867ad1b8f7fcc7b92b0

@nsavinda
