### ISSUE TITLE
Update FAQ section

### ISSUE THREAD

**Issue by nsavinda** [IEEEUCSC/madhack-2024#50]
1. What is MadHack 3.0?
   - MadHack 3.0 is a coding competition where enthusiasts come together to showcase their skills in mobile app development. It's a platform to learn, collaborate, and compete in creating innovative solutions for real-world challenges.

2. Who can participate in MadHack 3.0?
   - MadHack 3.0 is open to all undergraduate students! Whether you're a seasoned developer or just starting, we welcome participants of all skill levels and backgrounds.

3. How can I register for MadHack 3.0?
   - To register, visit our website and navigate to the registration page. Fill in the required details for yourself and your team members (if applicable) to secure your spot.

4. Do I need a team to participate?
   - Yes, for the Initial Round and the Final Hackathon, participants are encouraged to form teams of four members each.

5. What if I'm a beginner in coding? Can I still participate?
   - Absolutely! MadHack 3.0 is designed for participants of all skill levels. It's a great opportunity for beginners to learn and for experienced coders to showcase their expertise.

6. Is the usage of Flutter mandatory for MadHack 3.0 projects?
   - No, it's not mandatory to use Flutter for your projects in MadHack 3.0. While we have Flutter sessions to help you, you are free to use other frameworks or technologies that best suit your project requirements.

**Comment by Udeesha-Prabhashana** [comment]
Done
